'use strict';
/* Blocos 2 — mais cinquenta vistas para uma caixa. Cada uma recebe a caixa e os blocos já filtrados.
   MV[id] = [nome, categoria, descrição, função]. Soltar um bloco numa área `data-drop="g"` passa por gdrop(). */

const ab = l => l.filter(b => !b.feito);
const tar = l => l.filter(b => b.forma !== 'nota');
const ponto = c => c ? `<i class="dot" style="background:${c}"></i>` : '';
const gcol = (modo, id, nome, bs, cor) => `<section class="kcol" data-drop="g" data-modo="${modo}" data-col="${esc(id)}"><header>${ponto(cor)}<b>${esc(nome)}</b><span class="muted">${bs.length} · peso ${somaPeso(bs)}</span></header>${bs.map(b => card(b)).join('') || '<p class="kvazio">solte um bloco aqui</p>'}</section>`;
const gboard = cols => `<div class="kb">${cols.join('')}</div>`;
const sec = (tit, bs, o) => bs.length ? `<h4>${tit} <span class="muted">${bs.length}</span></h4>${bs.map(b => card(b, o)).join('')}` : '';
const nada = t => `<p class="empty">${t}</p>`;
const barra = (nome, cor, n, mx, txt) => `<div class="bar"><span class="bl">${ponto(cor)}${esc(nome)}</span><span class="bt"><i style="width:${mx ? n / mx * 100 : 0}%;background:${cor || 'var(--ink)'}"></i></span><span class="bv">${txt}</span></div>`;
const diasAte = d => Math.round((parse(d) - parse(today())) / 864e5);
const prioOrd = (a, b) => b.prio - a.prio || (b.estrela - a.estrela) || (a.prazo || '9').localeCompare(b.prazo || '9');
const PRIOS = ['Sem prioridade', 'Baixa !', 'Média !!', 'Alta !!!'];
const faixa = b => { const t = today(); return !b.prazo ? 'sem' : b.prazo < t ? 'atrasado' : b.prazo === t ? 'hoje' : b.prazo === addDays(t, 1) ? 'amanha' : b.prazo <= addDays(t, 7) ? 'semana' : 'depois'; };
const importante = b => b.prio >= 2 || b.estrela, urgente = b => !!b.prazo && b.prazo <= addDays(today(), 2);
const periodo = b => !b.hora ? '' : b.hora < '12:00' ? '09:00' : b.hora < '18:00' ? '14:00' : '19:00';
const dataDe = ts => ymd(new Date(ts));
const chip = b => `<span class="cchip${b.feito ? ' feito' : ''}" draggable="true" data-act="abrir" data-id="${b.id}" style="--c:${corDe(b.cor).cor};--ink:${ink(corDe(b.cor).cor)}">${esc(b.titulo) || 'Sem título'}</span>`;
const grande = (b, botoes) => { const c = corDe(b.cor), k = filhos(b.id); return `<article class="um" style="--c:${c.cor}"><p class="muted sm">${esc(c.nome)}${b.prazo ? ' · ' + fmtDia(b.prazo) + (b.hora ? ' ' + b.hora : '') : ''}${b.prio ? ' · ' + '!'.repeat(b.prio) : ''}</p><h2>${esc(b.titulo) || 'Sem título'}</h2>${b.texto ? `<div class="md">${md(b.texto, b.id)}</div>` : ''}${k.map(x => card(x)).join('')}<div class="acts">${botoes}</div></article>`; };

const MV = {
  /* ----- Quadros por propriedade ----- */
  'k-etiqueta': ['Quadro por etiqueta', 'Quadros', 'Uma coluna por cor. Soltar troca a etiqueta.', (cx, l) => gboard(cores().concat(SEM_COR).map(c => gcol('etiqueta', c.id, c.nome, ab(l).filter(b => corDe(b.cor).id === c.id), c.cor)))],
  'k-prio': ['Quadro por prioridade', 'Quadros', 'De alta a nenhuma. Soltar muda a prioridade.', (cx, l) => gboard([3, 2, 1, 0].map(p => gcol('prio', p, PRIOS[p], ab(l).filter(b => b.prio === p))))],
  'k-peso': ['Quadro por peso', 'Quadros', 'Peças de 1, 2 e 3 pinos lado a lado.', (cx, l) => gboard([1, 2, 3].map(p => gcol('peso', p, plural(p, 'pino', 'pinos'), ab(l).filter(b => b.peso === p))))],
  'k-prazo': ['Quadro por prazo', 'Quadros', 'Atrasado, hoje, amanhã, semana, depois, sem prazo.', (cx, l) => gboard([['atrasado', 'Atrasados'], ['hoje', 'Hoje'], ['amanha', 'Amanhã'], ['semana', 'Esta semana'], ['depois', 'Depois'], ['sem', 'Sem prazo']].map(([id, n]) => gcol('prazo', id, n, ab(l).filter(b => faixa(b) === id).sort(prioOrd), id === 'atrasado' ? 'var(--bad)' : '')))],
  'k-semana': ['Semana em colunas', 'Quadros', 'Os próximos sete dias, um por coluna.', (cx, l) => { const t = today(); return gboard(Array.from({ length: 7 }, (_, i) => addDays(t, i)).map(d => gcol('dia', d, fmtDia(d), l.filter(b => b.prazo === d))).concat(gcol('dia', 'sem', 'Sem prazo', ab(l).filter(b => !b.prazo)))); }],
  'k-estado': ['Quadro por estado', 'Quadros', 'Abertos, no meu dia e concluídos.', (cx, l) => { const t = today(), dia = b => !b.feito && (b.hoje === t || b.prazo === t); return gboard([gcol('estado', 'aberto', 'Abertos', l.filter(b => !b.feito && !dia(b))), gcol('estado', 'dia', 'No meu dia', l.filter(dia)), gcol('estado', 'feito', 'Concluídos', l.filter(b => b.feito).sort((a, b) => b.feito - a.feito).slice(0, 40), 'var(--ok)')]); }],
  'k-tipo': ['Tarefas e notas', 'Quadros', 'Duas colunas. Soltar converte o bloco.', (cx, l) => gboard([gcol('tipo', 'tarefa', 'Tarefas', l.filter(b => b.forma !== 'nota' && !b.feito)), gcol('tipo', 'nota', 'Notas', l.filter(b => b.forma === 'nota'))])],
  'k-tag': ['Quadro por etiqueta livre', 'Quadros', 'Uma coluna por #etiqueta que você escreveu.', (cx, l) => { const n = {}; ab(l).forEach(b => tagsDe(b).forEach(t => { n[t] = (n[t] || 0) + 1; })); const ts = Object.keys(n).sort((a, b) => n[b] - n[a]).slice(0, 10); return gboard(ts.map(t => gcol('tag', t, '#' + t, ab(l).filter(b => tagsDe(b).includes(t)))).concat(gcol('tag', '', 'Sem etiqueta livre', ab(l).filter(b => !tagsDe(b).length)))); }],
  'k-repete': ['Quadro de rotinas', 'Quadros', 'O que se repete e com que frequência.', (cx, l) => gboard(Object.entries(REPETE).map(([id, n]) => gcol('repete', id, n, ab(l).filter(b => b.repete === id))))],
  'k-progresso': ['Quadro de progresso', 'Quadros', 'Pelo andamento dos blocos de dentro.', (cx, l) => { const p = b => { const k = filhos(b.id), d = k.filter(x => x.feito).length; return !k.length ? 0 : !d ? 1 : d < k.length ? 2 : 3; }; return gboard(['Sem blocos dentro', 'Nada encaixado', 'Em andamento', 'Tudo encaixado'].map((n, i) => gcol('x', i, n, ab(l).filter(b => p(b) === i)))); }],
  'k-estrela': ['Destaques', 'Quadros', 'Fixados, com estrela e o resto.', (cx, l) => gboard([gcol('estrela', 'fixo', 'Fixados ◆', ab(l).filter(b => b.fixo)), gcol('estrela', 'estrela', 'Com estrela ★', ab(l).filter(b => b.estrela && !b.fixo)), gcol('estrela', '', 'Demais', ab(l).filter(b => !b.estrela && !b.fixo))])],

  /* ----- Matrizes ----- */
  'eisenhower': ['Matriz de Eisenhower', 'Matrizes', 'Importante × urgente, em quatro quadrantes.', (cx, l) => { const a = tar(ab(l)), q = (i, u, t, s) => `<section class="kcol q${i}${u}" data-drop="g" data-modo="eis" data-col="${i}${u}"><header><b>${t}</b><span class="muted">${s}</span></header>${a.filter(b => +importante(b) === i && +urgente(b) === u).sort(prioOrd).map(b => card(b)).join('') || '<p class="kvazio">vazio</p>'}</section>`;
    return `<div class="quad">${q(1, 1, 'Fazer agora', 'importante e urgente')}${q(1, 0, 'Agendar', 'importante, sem pressa')}${q(0, 1, 'Encurtar ou delegar', 'urgente, pouco importante')}${q(0, 0, 'Deixar para depois', 'nem um, nem outro')}</div><p class="muted sm hint">Importante: prioridade !! ou mais, ou estrela. Urgente: prazo em até dois dias.</p>`; }],
  'esforco': ['Matriz peso × prioridade', 'Matrizes', 'Acha os ganhos rápidos: muita prioridade, pouco peso.', (cx, l) => { const a = tar(ab(l)); return `<div class="mx"><span></span>${[1, 2, 3].map(p => `<b>${plural(p, 'pino', 'pinos')}</b>`).join('')}${[3, 2, 1, 0].map(pr => `<b>${PRIOS[pr]}</b>` + [1, 2, 3].map(p => `<div class="cel${pr >= 2 && p === 1 ? ' bom' : ''}" data-drop="g" data-modo="esf" data-col="${pr}-${p}">${a.filter(b => b.prio === pr && b.peso === p).map(b => card(b)).join('')}</div>`).join('')).join('')}</div><p class="muted sm hint">Os quadros verdes são os ganhos rápidos.</p>`; }],

  /* ----- Listas ----- */
  'agenda': ['Agenda da caixa', 'Listas', 'Em ordem de data, com um cabeçalho por dia.', (cx, l) => { const a = ab(l).filter(b => b.prazo), ds = [...new Set(a.map(b => b.prazo))].sort(); return ds.map(d => `<section data-drop="g" data-modo="dia" data-col="${d}">${sec(`${fmtDia(d)} <span class="muted">${fmtData(d, { day: 'numeric', month: 'long' })}</span>`, a.filter(b => b.prazo === d).sort((x, y) => (x.hora || '99').localeCompare(y.hora || '99')))}</section>`).join('') + sec('Sem prazo', ab(l).filter(b => !b.prazo)) || nada('Nenhum bloco aberto.'); }],
  'hora': ['Linha do dia', 'Listas', 'As horas de hoje, das 6h às 22h.', (cx, l) => { const t = today(), a = ab(l).filter(b => b.prazo === t || b.hoje === t); return sec('Sem hora marcada', a.filter(b => !b.hora)) + `<div class="horario">${Array.from({ length: 17 }, (_, i) => i + 6).map(h => `<div class="hr" data-drop="g" data-modo="hora" data-col="${t}|${pad(h)}:00"><b>${h}h</b><div>${a.filter(b => b.hora && +b.hora.slice(0, 2) === h).map(b => card(b)).join('')}</div></div>`).join('')}</div>`; }],
  'alfabeto': ['Índice alfabético', 'Listas', 'De A a Z, pela primeira letra.', (cx, l) => { const g = {}; l.forEach(b => { const k = (norma(b.titulo)[0] || '#').toUpperCase(), c = /[A-Z]/.test(k) ? k : '#'; (g[c] = g[c] || []).push(b); }); return Object.keys(g).sort().map(k => sec(k, g[k].sort((a, b) => a.titulo.localeCompare(b.titulo, 'pt')))).join('') || nada('Nenhum bloco.'); }],
  'atrasados': ['Pendências', 'Listas', 'Só os atrasados, do mais antigo ao mais recente.', (cx, l) => l.filter(atrasado).sort((a, b) => a.prazo.localeCompare(b.prazo)).map(b => card(b, { mais: `<span class="pill">${plural(-diasAte(b.prazo), 'dia', 'dias')}</span>` })).join('') || nada('Nenhum bloco atrasado nesta caixa.')],
  'lacunas': ['O que falta definir', 'Listas', 'Tarefas sem prazo, sem etiqueta ou sem prioridade.', (cx, l) => { const a = tar(ab(l)); return sec('Sem prazo', a.filter(b => !b.prazo)) + sec('Sem etiqueta', a.filter(b => !b.cor)) + sec('Sem prioridade', a.filter(b => !b.prio)) || nada('Tudo definido: toda tarefa tem prazo, etiqueta e prioridade.'); }],
  'atividade': ['Atividade recente', 'Listas', 'O que mudou por último, do mais novo ao mais antigo.', (cx, l) => { const t = today(), f = b => { const d = dataDe(b.mod); return d === t ? 0 : d === addDays(t, -1) ? 1 : d >= addDays(t, -7) ? 2 : 3; }, o = l.slice().sort((a, b) => b.mod - a.mod); return ['Hoje', 'Ontem', 'Nos últimos 7 dias', 'Antes'].map((n, i) => sec(n, o.filter(b => f(b) === i))).join('') || nada('Nenhum bloco.'); }],
  'diario': ['Diário de concluídos', 'Listas', 'O que foi concluído, dia por dia.', (cx, l) => { const f = l.filter(b => b.feito).sort((a, b) => b.feito - a.feito), ds = [...new Set(f.map(b => dataDe(b.feito)))]; return ds.map(d => sec(`${fmtDia(d)} <span class="muted">${fmtData(d, { day: 'numeric', month: 'long' })}</span>`, f.filter(b => dataDe(b.feito) === d))).join('') || nada('Nada concluído ainda (ou os concluídos estão escondidos no filtro).'); }],
  'arvore': ['Árvore de encaixes', 'Listas', 'Todos os níveis abertos, como um sumário.', (cx, l) => { const no = b => `<li><label><input type="checkbox" data-chk="${b.id}" ${b.feito ? 'checked' : ''} ${b.forma === 'nota' ? 'disabled' : ''}></label><a href="#" data-act="abrir" data-id="${b.id}" class="${b.feito ? 'feito' : ''}">${ponto(corDe(b.cor).cor)}${esc(b.titulo) || 'Sem título'}</a>${filhos(b.id).length ? `<ul>${filhos(b.id).map(no).join('')}</ul>` : ''}</li>`; return l.length ? `<ul class="arv">${l.slice().sort(ordB).map(no).join('')}</ul>` : nada('Nenhum bloco.'); }],
  'imprimir': ['Folha para imprimir', 'Listas', 'Lista limpa com caixinhas, pronta para o papel.', (cx, l) => { const no = (b, n) => `<div class="pl" style="margin-left:${n * 22}px"><i></i><span>${esc(b.titulo)}${b.prazo ? ` <small>${fmtData(b.prazo, { day: 'numeric', month: 'short' })}</small>` : ''}</span></div>${filhos(b.id).filter(x => !x.feito).map(x => no(x, n + 1)).join('')}`; return `<div class="tools"><button class="btn pri sm" data-act="imprimir">Imprimir</button></div><div class="folha"><h2>${esc(cx.nome)}</h2>${colsDe(cx.id).map(c => { const bs = ab(l).filter(b => b.coluna === c.id).sort(ordB); return bs.length ? `<h4>${esc(c.nome)}</h4>${bs.map(b => no(b, 0)).join('')}` : ''; }).join('')}</div>`; }],
  'links': ['Favoritos', 'Listas', 'Só os blocos que têm link, como uma lista de sites.', (cx, l) => { const a = l.flatMap(b => [b, ...filhos(b.id)]).filter(b => b.link); return a.map(b => `<div class="rowl"><div class="grow">${ponto(corDe(b.cor).cor)} <a href="#" data-act="abrir" data-id="${b.id}"><b>${esc(b.titulo) || 'Sem título'}</b></a><br><a class="muted sm" href="${esc(/^https?:\/\//i.test(b.link) ? b.link : 'https://' + b.link)}" target="_blank" rel="noopener">${esc(b.link)}</a></div></div>`).join('') || nada('Nenhum bloco com link nesta caixa.'); }],

  /* ----- Um por vez ----- */
  'foco': ['Foco: um bloco por vez', 'Um por vez', 'Só o mais importante na tela. Conclua ou pule.', (cx, l) => { const a = tar(ab(l)).sort(prioOrd); if (!a.length) return nada('Nada aberto. A caixa está em dia.'); const b = a[(U.pulo || 0) % a.length]; return `<p class="muted sm">${(U.pulo || 0) % a.length + 1} de ${a.length}, pela prioridade e pelo prazo</p>` + grande(b, `<button class="btn pri" data-act="check" data-id="${b.id}">Concluir</button><button class="btn" data-act="um" data-k="pulo" data-n="1">Pular</button><button class="btn" data-act="abrir" data-id="${b.id}">Abrir o cartão</button>`); }],
  'triagem': ['Triagem', 'Um por vez', 'Decide prazo e etiqueta de um bloco por vez.', (cx, l) => { const a = tar(ab(l)).filter(b => !b.prazo || !b.cor); if (!a.length) return nada('Triagem feita: todo bloco tem prazo e etiqueta.'); const b = a[(U.pulo || 0) % a.length]; return `<p class="muted sm">Faltam ${plural(a.length, 'bloco', 'blocos')} para triar</p>` + grande(b, `<button class="btn pri" data-act="prazo" data-id="${b.id}" data-n="0">Hoje</button><button class="btn" data-act="prazo" data-id="${b.id}" data-n="1">Amanhã</button><button class="btn" data-act="prazo" data-id="${b.id}" data-n="7">Em uma semana</button><button class="btn" data-act="um" data-k="pulo" data-n="1">Pular</button><button class="btn danger" data-act="lixo" data-id="${b.id}">Lixeira</button>`) + `<div class="chips">${cores().map(x => `<button class="cor ${b.cor === x.id ? 'on' : ''}" data-act="prop" data-id="${b.id}" data-k="cor" data-v="${x.id}" style="--c:${x.cor};--ink:${ink(x.cor)}">${esc(x.nome)}</button>`).join('')}</div>`; }],
  'flash': ['Cartões de estudo', 'Um por vez', 'O título na frente, o texto no verso. Vire para conferir.', (cx, l) => { const a = l.filter(b => b.texto); if (!a.length) return nada('Escreva texto em um bloco: o título vira a pergunta e o texto, a resposta.'); const i = (((U.fi || 0) % a.length) + a.length) % a.length, b = a[i]; return `<p class="muted sm">Cartão ${i + 1} de ${a.length}</p><article class="um flash" style="--c:${corDe(b.cor).cor}" data-act="virarF" role="button" tabindex="0"><h2>${esc(b.titulo) || 'Sem título'}</h2>${U.fv ? `<div class="md">${md(b.texto)}</div>` : '<p class="muted">Toque para virar</p>'}</article><div class="acts"><button class="btn" data-act="um" data-k="fi" data-n="-1" data-z="fv">Anterior</button><button class="btn pri" data-act="virarF">Virar</button><button class="btn" data-act="um" data-k="fi" data-n="1" data-z="fv">Próximo</button></div>`; }],
  'sorteio': ['Sorteio', 'Um por vez', 'Não sabe por onde começar? Deixe a caixa escolher.', (cx, l) => { const a = tar(ab(l)), b = a.find(x => x.id === U.sorte); return `<div class="tools"><button class="btn pri" data-act="sortear">Sortear um bloco</button><span class="muted sm">${plural(a.length, 'bloco aberto', 'blocos abertos')} no pote</span></div>` + (b ? grande(b, `<button class="btn pri" data-act="check" data-id="${b.id}">Concluir</button><button class="btn" data-act="hoje" data-id="${b.id}">Pôr no meu dia</button><button class="btn" data-act="abrir" data-id="${b.id}">Abrir o cartão</button>`) : nada('Aperte o botão para tirar um bloco.')); }],

  /* ----- Notas e leitura ----- */
  'leitura': ['Leitura contínua', 'Notas', 'Todos os textos em sequência, como um documento.', (cx, l) => l.filter(b => b.texto).sort(ordB).map(b => `<article class="doc"><h2 data-act="abrir" data-id="${b.id}" role="button" tabindex="0">${esc(b.titulo) || 'Sem título'}</h2><div class="md">${md(b.texto, b.id)}</div></article>`).join('') || nada('Nenhum bloco com texto nesta caixa.')],
  'galeria': ['Galeria', 'Notas', 'Cartões grandes com capa na cor da etiqueta.', (cx, l) => `<div class="gal">${l.slice().sort(ordB).map(b => { const c = corDe(b.cor), k = filhos(b.id); return `<article class="gl${b.feito ? ' feito' : ''}" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" draggable="true"><div class="capa" style="--c:${c.cor};--ink:${ink(c.cor)}">${b.estrela ? '★' : ''}${'<i></i>'.repeat(b.peso)}</div><h3>${esc(b.titulo) || 'Sem título'}</h3><p class="muted sm">${esc(c.nome)}${b.prazo ? ' · ' + fmtDia(b.prazo) : ''}${k.length ? ` · ${k.filter(x => x.feito).length}/${k.length}` : ''}</p></article>`; }).join('')}</div>` || nada('Nenhum bloco.')],
  'mural': ['Mural de lembretes', 'Notas', 'Papéis coloridos colados na parede.', (cx, l) => `<div class="mural">${ab(l).map(b => `<article class="post" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" draggable="true" style="--c:${corDe(b.cor).cor}"><b>${esc(b.titulo) || 'Sem título'}</b>${b.texto ? `<p>${esc(b.texto.replace(/[#*`>\[\]-]/g, '').slice(0, 110))}</p>` : ''}${b.prazo ? `<small>${fmtDia(b.prazo)}</small>` : ''}</article>`).join('')}</div>`],
  'sumario': ['Sumário das notas', 'Notas', 'Os títulos internos de cada texto, como um índice.', (cx, l) => l.filter(b => /^#{1,3}\s/m.test(b.texto)).map(b => `<div class="sm0"><a href="#" data-act="abrir" data-id="${b.id}"><b>${esc(b.titulo) || 'Sem título'}</b></a><ul class="arv">${b.texto.split('\n').filter(x => /^#{1,3}\s/.test(x)).map(x => `<li style="margin-left:${(x.match(/^#+/)[0].length - 1) * 16}px">${esc(x.replace(/^#+\s*/, ''))}</li>`).join('')}</ul></div>`).join('') || nada('Nenhum texto com títulos (linhas começando com #).')],
  'nuvem': ['Nuvem de etiquetas', 'Notas', 'As #etiquetas livres, maiores quanto mais usadas.', (cx, l) => { const n = {}; l.forEach(b => tagsDe(b).forEach(t => { n[t] = (n[t] || 0) + 1; })); const ts = Object.keys(n).sort(), mx = Math.max(1, ...Object.values(n)); return ts.length ? `<div class="nuvem">${ts.map(t => `<button data-act="filtroTag" data-v="${esc(t)}" style="font-size:${13 + n[t] / mx * 22}px">#${esc(t)} <small>${n[t]}</small></button>`).join('')}</div><p class="muted sm hint">Toque numa etiqueta para ver a lista só com ela.</p>` : nada('Nenhuma etiqueta livre. Na captura, escreva #palavra.'); }],

  /* ----- Tempo ----- */
  'semgrade': ['Semana em grade', 'Tempo', 'Sete dias por quatro períodos do dia.', (cx, l) => { const t = today(), ds = Array.from({ length: 7 }, (_, i) => addDays(t, i)); return `<div class="tw"><div class="sg"><span></span>${ds.map(d => `<b>${fmtDia(d)}</b>`).join('')}${[['', 'Dia todo'], ['09:00', 'Manhã'], ['14:00', 'Tarde'], ['19:00', 'Noite']].map(([h, n]) => `<b>${n}</b>` + ds.map(d => `<div class="cel" data-drop="g" data-modo="periodo" data-col="${d}|${h}">${l.filter(b => b.prazo === d && periodo(b) === h).map(chip).join('')}</div>`).join('')).join('')}</div></div>${sec('Sem prazo: arraste para a grade', ab(l).filter(b => !b.prazo).slice(0, 20))}`; }],
  'ano': ['Ano inteiro', 'Tempo', 'Doze meses de uma vez; os dias com prazo ficam marcados.', (cx, l) => { const y = +today().slice(0, 4), n = {}; l.forEach(b => { if (b.prazo) n[b.prazo] = (n[b.prazo] || 0) + 1; }); return `<div class="ano">${Array.from({ length: 12 }, (_, m) => { const p = new Date(y, m, 1), dias = new Date(y, m + 1, 0).getDate(); return `<div><b>${p.toLocaleDateString('pt-BR', { month: 'long' })}</b><div class="am">${'<i class="hx"></i>'.repeat((p.getDay() + 6) % 7)}${Array.from({ length: dias }, (_, i) => { const d = `${y}-${pad(m + 1)}-${pad(i + 1)}`, c = n[d] || 0; return `<i class="h${Math.min(4, c)}${d === today() ? ' hj' : ''}" data-drop="g" data-modo="dia" data-col="${d}" title="${i + 1}: ${c ? plural(c, 'bloco', 'blocos') : 'livre'}"></i>`; }).join('')}</div></div>`; }).join('')}</div>`; }],
  'gantt': ['Linha do tempo', 'Tempo', 'Uma barra por bloco, de hoje até o prazo (28 dias).', (cx, l) => { const a = tar(ab(l)).filter(b => b.prazo).sort((x, y) => x.prazo.localeCompare(y.prazo)); return a.length ? `<div class="gantt">${a.map(b => { const d = diasAte(b.prazo), c = corDe(b.cor).cor; return `<div class="gr" data-act="abrir" data-id="${b.id}" role="button" tabindex="0"><span>${esc(b.titulo)}</span><div><i style="width:${Math.max(3, Math.min(100, (d + 1) / 28 * 100))}%;background:${d < 0 ? 'var(--bad)' : c}"></i><small>${d < 0 ? `atrasado ${plural(-d, 'dia', 'dias')}` : d === 0 ? 'hoje' : `${plural(d, 'dia', 'dias')}`}</small></div></div>`; }).join('')}</div>` : nada('Nenhuma tarefa aberta com prazo.'); }],
  'contagem': ['Contagem regressiva', 'Tempo', 'Quantos dias faltam para cada prazo, em números grandes.', (cx, l) => { const a = ab(l).filter(b => b.prazo).sort((x, y) => x.prazo.localeCompare(y.prazo)); return a.length ? `<div class="gal">${a.map(b => { const d = diasAte(b.prazo); return `<article class="gl cont" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${corDe(b.cor).cor}"><b class="${d < 0 ? 'bad' : ''}">${Math.abs(d)}</b><span class="muted sm">${d < 0 ? (d === -1 ? 'dia de atraso' : 'dias de atraso') : d === 0 ? 'é hoje' : d === 1 ? 'dia' : 'dias'}</span><h3>${esc(b.titulo)}</h3></article>`; }).join('')}</div>` : nada('Nenhum bloco aberto com prazo.'); }],
  'calor': ['Mapa de calor', 'Tempo', 'Dezesseis semanas de blocos concluídos nesta caixa.', (cx, l) => { const n = {}; S.blocos.filter(b => b.caixa === cx.id && b.feito && !b.lixo).forEach(b => { const d = dataDe(b.feito); n[d] = (n[d] || 0) + 1; }); const t = today(), ini = addDays(t, -((parse(t).getDay() + 6) % 7) - 7 * 15); return `<div class="calor gr16">${Array.from({ length: 16 }, (_, w) => `<div>${Array.from({ length: 7 }, (_, i) => { const d = addDays(ini, w * 7 + i), c = d > t ? -1 : n[d] || 0; return `<i class="h${c < 0 ? 'x' : Math.min(4, c)}" title="${fmtData(d, { day: 'numeric', month: 'short' })}: ${c > 0 ? c : 'nada'}"></i>`; }).join('')}</div>`).join('')}</div><p class="muted sm hint">Cada quadrado é um dia; quanto mais escuro, mais blocos concluídos (contando os de dentro).</p>`; }],

  /* ----- Análise ----- */
  'rosca': ['Rosca por etiqueta', 'Análise', 'A fatia de cada cor entre os blocos abertos.', (cx, l) => { const a = ab(l), r = cores().concat(SEM_COR).map(c => ({ c, n: a.filter(b => corDe(b.cor).id === c.id).length })).filter(x => x.n); let ac = 0; const g = r.map(x => { const de = ac; ac += x.n / a.length * 100; return `${x.c.cor} ${de}% ${ac}%`; }).join(', '); return a.length ? `<div class="rosca"><div class="ro" style="background:conic-gradient(${g})"><b>${a.length}<small>abertos</small></b></div><div class="grow">${r.map(x => barra(x.c.nome, x.c.cor, x.n, a.length, `${x.n} · ${Math.round(x.n / a.length * 100)}%`)).join('')}</div></div>` : nada('Nenhum bloco aberto.'); }],
  'funil': ['Funil das colunas', 'Análise', 'Quantos blocos há em cada etapa.', (cx, l) => { const r = colsDe(cx.id).map(c => ({ c, bs: l.filter(b => b.coluna === c.id) })), mx = Math.max(1, ...r.map(x => x.bs.length)); return `<div class="funil">${r.map(x => `<div><span style="width:${Math.max(8, x.bs.length / mx * 100)}%" class="${x.c.feito ? 'ok' : ''}">${esc(x.c.nome)} · ${x.bs.length}</span><small class="muted">peso ${somaPeso(x.bs)}${x.c.limite ? ` · limite ${x.c.limite}` : ''}</small></div>`).join('')}</div>`; }],
  'burn': ['Criados × concluídos', 'Análise', 'Trinta dias: o que entrou e o que saiu, acumulado.', (cx, l) => { const t = today(), ds = Array.from({ length: 30 }, (_, i) => addDays(t, i - 29)), a = tar(l), cr = ds.map(d => a.filter(b => b.criado && dataDe(b.criado) <= d).length), fe = ds.map(d => a.filter(b => b.feito && dataDe(b.feito) <= d).length), mx = Math.max(1, ...cr), pts = v => v.map((n, i) => `${(i / 29 * 300).toFixed(1)},${(100 - n / mx * 96).toFixed(1)}`).join(' '); return `<div class="panel"><svg viewBox="0 0 300 104" class="graf" role="img" aria-label="Criados e concluídos em 30 dias"><polyline points="${pts(cr)}" fill="none" stroke="var(--muted)" stroke-width="2"/><polyline points="${pts(fe)}" fill="none" stroke="var(--ok)" stroke-width="2.5"/></svg><p class="sm"><span class="muted">▬ criados: ${cr[29]}</span> · <span style="color:var(--ok)">▬ concluídos: ${fe[29]}</span> · abertos: ${cr[29] - fe[29]}</p><p class="muted sm">Quando as linhas se afastam, a caixa está enchendo mais rápido do que esvazia.</p></div>`; }],
  'prazos': ['Histograma de prazos', 'Análise', 'Quantos blocos vencem em cada uma das próximas semanas.', (cx, l) => { const a = ab(l), t = today(), seg = addDays(t, -((parse(t).getDay() + 6) % 7)), r = [['Atrasados', a.filter(atrasado).length, 'var(--bad)']].concat(Array.from({ length: 8 }, (_, i) => { const de = addDays(seg, i * 7), ate = addDays(de, 6); return [i ? `Semana de ${fmtData(de, { day: 'numeric', month: 'short' })}` : 'Esta semana', a.filter(b => b.prazo >= (i ? de : t) && b.prazo <= ate).length, '']; }), [['Sem prazo', a.filter(b => !b.prazo).length, 'var(--muted)']]), mx = Math.max(1, ...r.map(x => x[1])); return `<div class="panel">${r.map(x => barra(x[0], x[2], x[1], mx, String(x[1]))).join('')}</div>`; }],
  'balanca': ['Balança por etiqueta', 'Análise', 'Peso aberto contra peso concluído, cor por cor.', (cx, l) => { const r = cores().concat(SEM_COR).map(c => { const bs = l.filter(b => corDe(b.cor).id === c.id); return { c, a: somaPeso(ab(bs)), f: somaPeso(bs.filter(b => b.feito)) }; }).filter(x => x.a + x.f), mx = Math.max(1, ...r.map(x => Math.max(x.a, x.f))); return r.length ? `<div class="panel">${r.map(x => `<h4>${ponto(x.c.cor)}${esc(x.c.nome)}</h4>${barra('Aberto', x.c.cor, x.a, mx, String(x.a))}${barra('Concluído', 'var(--ok)', x.f, mx, String(x.f))}`).join('')}</div>` : nada('Nenhum bloco.'); }],
  'resumo': ['Resumo da caixa', 'Análise', 'Os números da caixa em uma tela.', (cx, l) => { const a = tar(l), abs = ab(a), fe = a.filter(b => b.feito), at = abs.filter(atrasado), px = abs.filter(b => b.prazo && !atrasado(b)).sort((x, y) => x.prazo.localeCompare(y.prazo)).slice(0, 5), gr = l.map(b => ({ b, n: filhos(b.id).length })).filter(x => x.n).sort((x, y) => y.n - x.n).slice(0, 5); return `<div class="stats s4"><div class="panel stat"><b>${abs.length}</b><span>tarefas abertas</span></div><div class="panel stat${at.length ? ' warn' : ''}"><b>${at.length}</b><span>atrasadas</span></div><div class="panel stat"><b>${a.length ? Math.round(fe.length / a.length * 100) : 0}%</b><span>concluído · ${fe.length} de ${a.length}</span></div><div class="panel stat"><b>${somaPeso(abs)}</b><span>de peso aberto · ${l.filter(b => b.forma === 'nota').length} notas</span></div></div><div class="cols"><section class="panel"><h3>Próximos prazos</h3>${px.map(b => card(b)).join('') || '<p class="muted sm">Nenhum prazo à frente.</p>'}</section><section class="panel"><h3>Blocos com mais peças dentro</h3>${gr.map(x => card(x.b)).join('') || '<p class="muted sm">Nenhum bloco tem blocos dentro.</p>'}</section></div>`; }],
  'ritmo': ['Ritmo da semana', 'Análise', 'Em que dia da semana você mais conclui nesta caixa.', (cx, l) => { const n = [0, 0, 0, 0, 0, 0, 0]; S.blocos.filter(b => b.caixa === cx.id && b.feito && !b.lixo).forEach(b => n[(new Date(b.feito).getDay() + 6) % 7]++); const mx = Math.max(1, ...n), tot = n.reduce((a, b) => a + b, 0); return `<div class="panel">${['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'].map((d, i) => barra(d, '', n[i], mx, String(n[i]))).join('')}<p class="muted sm hint">${tot ? `Seu dia mais forte aqui é ${['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'][n.indexOf(mx)]}.` : 'Nada concluído nesta caixa ainda.'}</p></div>`; }],

  /* ----- Peças ----- */
  'torre': ['Torre', 'Peças', 'Uma pilha só: concluídos na base, abertos em contorno no alto.', (cx, l) => { const pc = (b, g) => `<div class="tj${g ? ' ghost' : ''}" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${corDe(b.cor).cor};--ink:${ink(corDe(b.cor).cor)};--w:${40 + b.peso * 20}%">${esc(b.titulo) || 'Sem título'}</div>`; return l.length ? `<div class="torreg">${tar(ab(l)).sort(prioOrd).reverse().map(b => pc(b, 1)).join('')}${l.filter(b => b.feito).sort((a, b) => b.feito - a.feito).map(b => pc(b)).join('')}</div><p class="muted sm hint">O próximo a encaixar é o contorno mais de baixo: o mais prioritário.</p>` : nada('Nenhum bloco.'); }],
  'muro': ['Muro da caixa', 'Peças', 'Todos os blocos como tijolos: cheios os concluídos, vazados os abertos.', (cx, l) => l.length ? `<div class="muro mg">${l.slice().sort((a, b) => (!!b.feito - !!a.feito) || a.ordem - b.ordem).map(b => `<i class="${b.feito ? '' : 'ghost'}" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${corDe(b.cor).cor};--w:${b.peso * 34}px" title="${esc(b.titulo)}"></i>`).join('')}</div><p class="muted sm hint">${l.filter(b => b.feito).length} de ${plural(l.length, 'tijolo assentado', 'tijolos assentados')}.</p>` : nada('Nenhum bloco.')],
  'planta': ['Planta baixa', 'Peças', 'As colunas como cômodos, com uma pecinha por bloco.', (cx, l) => `<div class="planta">${colsDe(cx.id).map(c => { const bs = l.filter(b => b.coluna === c.id).sort(ordB); return `<section data-drop="col" data-col="${c.id}" class="${c.feito ? 'final' : ''}"><h4>${esc(c.nome)} <span class="muted">${bs.length}</span></h4><div>${bs.map(b => `<i class="${b.feito ? 'feito' : ''}" draggable="true" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${corDe(b.cor).cor};--w:${b.peso * 14}px" title="${esc(b.titulo)}"></i>`).join('')}</div></section>`; }).join('')}</div><p class="muted sm hint">Arraste uma pecinha de um cômodo para outro para mudar de coluna.</p>`],
  'pilhas': ['Pilhas por etiqueta', 'Peças', 'Um gráfico de barras feito de peças.', (cx, l) => `<div class="pilhas">${cores().concat(SEM_COR).map(c => { const bs = ab(l).filter(b => corDe(b.cor).id === c.id); return bs.length ? `<div data-drop="g" data-modo="etiqueta" data-col="${c.id}"><div class="pp">${bs.map(b => `<i draggable="true" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${c.cor};--h:${b.peso * 12}px" title="${esc(b.titulo)}"></i>`).join('')}</div><b>${esc(c.nome)}</b><span class="muted sm">${bs.length} · peso ${somaPeso(bs)}</span></div>` : ''; }).join('')}</div>`],

  /* ----- Estrutura ----- */
  'mapa': ['Mapa mental', 'Estrutura', 'A caixa no centro, os blocos e o que há dentro deles em ramos.', (cx, l) => { const no = b => `<li><span class="mn${b.feito ? ' feito' : ''}" data-act="abrir" data-id="${b.id}" role="button" tabindex="0" style="--c:${corDe(b.cor).cor}">${esc(b.titulo) || 'Sem título'}</span>${filhos(b.id).length ? `<ul>${filhos(b.id).map(no).join('')}</ul>` : ''}</li>`; return `<div class="tw mmw"><ul class="mm"><li><span class="mn raiz">${esc((cx.icone ? cx.icone + ' ' : '') + cx.nome)}</span><ul>${colsDe(cx.id).map(c => { const bs = l.filter(b => b.coluna === c.id).sort(ordB); return bs.length ? `<li><span class="mn col">${esc(c.nome)}</span><ul>${bs.map(no).join('')}</ul></li>` : ''; }).join('')}</ul></li></ul></div>`; }],
  'encaixes': ['Tabela de encaixes', 'Estrutura', 'Só os blocos que têm blocos dentro, com o progresso e o próximo passo.', (cx, l) => { const a = l.map(b => ({ b, k: filhos(b.id) })).filter(x => x.k.length); return a.length ? `<div class="tw"><table class="tab"><thead><tr><th>Bloco</th><th>Progresso</th><th>Dentro</th><th>Próximo passo</th></tr></thead><tbody>${a.map(x => { const d = x.k.filter(y => y.feito).length, px = x.k.find(y => !y.feito); return `<tr class="${x.b.feito ? 'feito' : ''}"><td class="tt" data-act="abrir" data-id="${x.b.id}" role="button" tabindex="0">${ponto(corDe(x.b.cor).cor)} ${esc(x.b.titulo)}</td><td style="min-width:120px"><div class="meter"><i style="width:${d / x.k.length * 100}%"></i></div></td><td>${d}/${x.k.length}</td><td>${px ? `<a href="#" data-act="abrir" data-id="${px.id}">${esc(px.titulo)}</a>` : '<span class="muted">tudo encaixado</span>'}</td></tr>`; }).join('')}</tbody></table></div>` : nada('Nenhum bloco tem blocos dentro. Abra um bloco e encaixe outros nele.'); }],
};

// soltar um bloco numa área das vistas novas: cada vista muda uma propriedade diferente
function gdrop(b, modo, col, e, z) {
  const t = today();
  if (modo === 'etiqueta') b.cor = col;
  else if (modo === 'prio') b.prio = +col;
  else if (modo === 'peso') b.peso = +col;
  else if (modo === 'prazo') { if (col === 'atrasado') return recusa(b.id, 'Atraso não se escolhe: solte em outro prazo.'); b.prazo = { hoje: t, amanha: addDays(t, 1), semana: addDays(t, 4), depois: addDays(t, 14), sem: '' }[col]; }
  else if (modo === 'dia') b.prazo = col === 'sem' ? '' : col;
  else if (modo === 'estado') { if (col === 'feito') { if (!b.feito) concluir(b.id, true); return; } if (b.feito) setFeito(b, false); b.hoje = col === 'dia' ? t : ''; }
  else if (modo === 'tipo') { b.forma = col; if (col === 'nota') b.feito = 0; }
  else if (modo === 'tag') { const ts = tagsDe(b); b.tags = col ? (ts.includes(col) ? ts : ts.concat(col)).join(', ') : ''; }
  else if (modo === 'repete') b.repete = col;
  else if (modo === 'estrela') { b.fixo = col === 'fixo'; b.estrela = col === 'estrela' || (col === 'fixo' && b.estrela); }
  else if (modo === 'eis') { const i = col[0] === '1', u = col[1] === '1'; if (i && !importante(b)) b.prio = 2; if (!i) { b.prio = Math.min(b.prio, 1); b.estrela = false; } if (u && !urgente(b)) b.prazo = t; if (!u && urgente(b)) b.prazo = addDays(t, 7); }
  else if (modo === 'esf') { const [pr, p] = col.split('-'); b.prio = +pr; b.peso = +p; }
  else if (modo === 'periodo') { const [d, h] = col.split('|'); b.prazo = d; if (!h) b.hora = ''; else if (periodo(b) !== h) b.hora = h; }
  else if (modo === 'hora') { const [d, h] = col.split('|'); b.prazo = d; b.hora = h; }
  else if (GX[modo]) { if (GX[modo](b, col, e, z) === false) return; }
  else return toast('Esta vista é só para olhar: aqui não dá para soltar.');
  Data.put('blocos', b); FX.mark(b.id, 'pop');
}

const CATS = ['Quadros', 'Matrizes', 'Listas', 'Um por vez', 'Notas', 'Tempo', 'Análise', 'Peças', 'Estrutura'];
function sheetVistas() {
  const cx = byId(S.caixas, U.caixa), bt = (id, n, d) => `<button class="vz${cx.vista === id ? ' on' : ''}" data-act="vista" data-v="${id}"><b>${n}</b><small>${d}</small></button>`;
  sheet(`<div class="shead"><b>Vistas da caixa</b><span class="muted sm">${Object.keys(MV).length + Object.keys(CV).length + VISTAS.length} jeitos de olhar os mesmos blocos</span><span class="grow"></span><button class="ib" data-act="fechar" aria-label="Fechar">✕</button></div>
    <h4>Clássicas</h4><div class="vzs">${bt('quadro', 'Quadro', 'Colunas para arrastar.')}${bt('lista', 'Lista', 'Tarefas com círculo de concluir.')}${bt('notas', 'Notas', 'Grade com a prévia do texto.')}${bt('tabela', 'Tabela', 'Uma linha por bloco.')}${bt('cal', 'Calendário', 'O mês inteiro.')}${Object.entries(CV).map(([id, v]) => bt(id, v[0], v[1])).join('')}</div>
    ${CATS.map(c => `<h4>${c}</h4><div class="vzs">${Object.entries(MV).filter(([, v]) => v[1] === c).map(([id, v]) => bt(id, v[0], v[2])).join('')}</div>`).join('')}`, 'card');
}
// ações das vistas novas; entram no mapa de ações do app
const A2 = {
  maisVistas() { sheetVistas(); },
  vista(el) {
    const c = byId(S.caixas, U.caixa), v = el.dataset.v; c.vista = v; Data.put('caixas', c);
    if (MV[v] || CV[v]) { S.set.rec = [v].concat((S.set.rec || []).filter(x => x !== v)).slice(0, 3); DB.saveSet(); }
    U.pulo = U.fi = U.slide = 0; U.fv = false; closeSheet(); draw();
  },
  um(el) { const d = el.dataset; U[d.k] = (U[d.k] || 0) + +d.n; if (d.z) U[d.z] = false; draw(); },
  virarF() { U.fv = !U.fv; draw(); FX.play($('.um.flash'), 'flip'); },
  sortear() { const a = tar(ab(raizes(U.caixa).filter(passa))).filter(b => b.id !== U.sorte); if (!a.length) return toast('Não há outro bloco aberto para sortear.'); U.sorte = a[Math.floor(Math.random() * a.length)].id; draw(); FX.play($('.um'), 'snap'); FX.pluck(); },
  filtroTag(el) { const c = byId(S.caixas, U.caixa); U.f.txt = el.dataset.v; c.vista = 'lista'; Data.put('caixas', c); draw(); },
  imprimir() { window.print(); },
};
